ktor:
#    development: true
    application:
        modules:
            - id.deval.ApplicationKt.module
        watch  :
            - classes
            - resources
    deployment:
        port: 8080
